import type { CourseSummary } from "./course-search.ts";

/** Display fixtures for the colocated stories, never app data. */
export const courseFixtures: CourseSummary[] = [
  {
    id: "english-basics",
    featured: true,
    title: "English basics",
    icon: "english-basics",
    subject: "languages",
    language: "en",
    ageRange: { minimum: 6, maximum: 12 },
    joined: false,
    totalUnits: 3,
    totalItems: 12,
    completedItems: 0,
    status: "not_started",
  },
  {
    id: "math-foundations",
    featured: true,
    title: "Math foundations",
    icon: "math-foundations",
    subject: "math",
    language: "en",
    ageRange: { minimum: 6, maximum: 9 },
    joined: true,
    totalUnits: 4,
    totalItems: 16,
    completedItems: 5,
    status: "in_progress",
  },
  {
    id: "vietnamese-basics",
    featured: false,
    title: "Vietnamese basics",
    icon: "vietnamese-basics",
    subject: "languages",
    language: "vi",
    ageRange: { minimum: 6, maximum: 12 },
    joined: false,
    totalUnits: 2,
    totalItems: 8,
    completedItems: 0,
    status: "not_started",
  },
  {
    id: "intro-to-code",
    featured: false,
    title: "Introduction to programming",
    icon: "intro-to-code",
    subject: "computer_science",
    language: "en",
    ageRange: { minimum: 13, maximum: 17 },
    joined: false,
    totalUnits: 6,
    totalItems: 24,
    completedItems: 0,
    status: "not_started",
  },
];
