/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAppearanceRouteImport } from './routes/_app.appearance'
import { Route as AppChallengesRouteImport } from './routes/_app.challenges'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppPlayRouteImport } from './routes/_app.play'
import { Route as AppRewardsRouteImport } from './routes/_app.rewards'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppWardrobeRouteImport } from './routes/_app.wardrobe'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app.courses.$courseId'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/_app.courses.$courseId.index'
import { Route as AppCoursesCourseIdLoadoutRouteImport } from './routes/_app.courses.$courseId.loadout'
import { Route as AppCoursesCourseIdShopRouteImport } from './routes/_app.courses.$courseId.shop'
import { Route as AppCoursesCourseIdLessonsItemIdRouteImport } from './routes/_app.courses.$courseId.lessons.$itemId'
import { Route as AppCoursesCourseIdPracticesItemIdSessionsSessionIdRouteImport } from './routes/_app.courses.$courseId.practices.$itemId.sessions.$sessionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppWardrobeRoute = AppWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesCourseIdRoute,
} as any)
const AppCoursesCourseIdLoadoutRoute =
  AppCoursesCourseIdLoadoutRouteImport.update({
    id: '/loadout',
    path: '/loadout',
    getParentRoute: () => AppCoursesCourseIdRoute,
  } as any)
const AppCoursesCourseIdShopRoute = AppCoursesCourseIdShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppCoursesCourseIdRoute,
} as any)
const AppCoursesCourseIdLessonsItemIdRoute =
  AppCoursesCourseIdLessonsItemIdRouteImport.update({
    id: '/lessons/$itemId',
    path: '/lessons/$itemId',
    getParentRoute: () => AppCoursesCourseIdRoute,
  } as any)
const AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute =
  AppCoursesCourseIdPracticesItemIdSessionsSessionIdRouteImport.update({
    id: '/practices/$itemId/sessions/$sessionId',
    path: '/practices/$itemId/sessions/$sessionId',
    getParentRoute: () => AppCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/appearance': typeof AppAppearanceRoute
  '/challenges': typeof AppChallengesRoute
  '/me': typeof AppMeRoute
  '/missions': typeof AppMissionsRoute
  '/play': typeof AppPlayRoute
  '/rewards': typeof AppRewardsRoute
  '/search': typeof AppSearchRoute
  '/shop': typeof AppShopRoute
  '/wardrobe': typeof AppWardrobeRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/courses/$courseId/loadout': typeof AppCoursesCourseIdLoadoutRoute
  '/courses/$courseId/shop': typeof AppCoursesCourseIdShopRoute
  '/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$itemId': typeof AppCoursesCourseIdLessonsItemIdRoute
  '/courses/$courseId/practices/$itemId/sessions/$sessionId': typeof AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/appearance': typeof AppAppearanceRoute
  '/challenges': typeof AppChallengesRoute
  '/me': typeof AppMeRoute
  '/missions': typeof AppMissionsRoute
  '/play': typeof AppPlayRoute
  '/rewards': typeof AppRewardsRoute
  '/search': typeof AppSearchRoute
  '/shop': typeof AppShopRoute
  '/wardrobe': typeof AppWardrobeRoute
  '/': typeof AppIndexRoute
  '/courses/$courseId/loadout': typeof AppCoursesCourseIdLoadoutRoute
  '/courses/$courseId/shop': typeof AppCoursesCourseIdShopRoute
  '/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/lessons/$itemId': typeof AppCoursesCourseIdLessonsItemIdRoute
  '/courses/$courseId/practices/$itemId/sessions/$sessionId': typeof AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/appearance': typeof AppAppearanceRoute
  '/_app/challenges': typeof AppChallengesRoute
  '/_app/me': typeof AppMeRoute
  '/_app/missions': typeof AppMissionsRoute
  '/_app/play': typeof AppPlayRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/wardrobe': typeof AppWardrobeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRouteWithChildren
  '/_app/courses/$courseId/loadout': typeof AppCoursesCourseIdLoadoutRoute
  '/_app/courses/$courseId/shop': typeof AppCoursesCourseIdShopRoute
  '/_app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/_app/courses/$courseId/lessons/$itemId': typeof AppCoursesCourseIdLessonsItemIdRoute
  '/_app/courses/$courseId/practices/$itemId/sessions/$sessionId': typeof AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/appearance'
    | '/challenges'
    | '/me'
    | '/missions'
    | '/play'
    | '/rewards'
    | '/search'
    | '/shop'
    | '/wardrobe'
    | '/courses/$courseId'
    | '/courses/$courseId/loadout'
    | '/courses/$courseId/shop'
    | '/courses/$courseId/'
    | '/courses/$courseId/lessons/$itemId'
    | '/courses/$courseId/practices/$itemId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/appearance'
    | '/challenges'
    | '/me'
    | '/missions'
    | '/play'
    | '/rewards'
    | '/search'
    | '/shop'
    | '/wardrobe'
    | '/'
    | '/courses/$courseId/loadout'
    | '/courses/$courseId/shop'
    | '/courses/$courseId'
    | '/courses/$courseId/lessons/$itemId'
    | '/courses/$courseId/practices/$itemId/sessions/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/appearance'
    | '/_app/challenges'
    | '/_app/me'
    | '/_app/missions'
    | '/_app/play'
    | '/_app/rewards'
    | '/_app/search'
    | '/_app/shop'
    | '/_app/wardrobe'
    | '/_app/'
    | '/_app/courses/$courseId'
    | '/_app/courses/$courseId/loadout'
    | '/_app/courses/$courseId/shop'
    | '/_app/courses/$courseId/'
    | '/_app/courses/$courseId/lessons/$itemId'
    | '/_app/courses/$courseId/practices/$itemId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appearance': {
      id: '/_app/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wardrobe': {
      id: '/_app/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof AppWardrobeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/': {
      id: '/_app/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
    '/_app/courses/$courseId/loadout': {
      id: '/_app/courses/$courseId/loadout'
      path: '/loadout'
      fullPath: '/courses/$courseId/loadout'
      preLoaderRoute: typeof AppCoursesCourseIdLoadoutRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
    '/_app/courses/$courseId/shop': {
      id: '/_app/courses/$courseId/shop'
      path: '/shop'
      fullPath: '/courses/$courseId/shop'
      preLoaderRoute: typeof AppCoursesCourseIdShopRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
    '/_app/courses/$courseId/lessons/$itemId': {
      id: '/_app/courses/$courseId/lessons/$itemId'
      path: '/lessons/$itemId'
      fullPath: '/courses/$courseId/lessons/$itemId'
      preLoaderRoute: typeof AppCoursesCourseIdLessonsItemIdRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
    '/_app/courses/$courseId/practices/$itemId/sessions/$sessionId': {
      id: '/_app/courses/$courseId/practices/$itemId/sessions/$sessionId'
      path: '/practices/$itemId/sessions/$sessionId'
      fullPath: '/courses/$courseId/practices/$itemId/sessions/$sessionId'
      preLoaderRoute: typeof AppCoursesCourseIdPracticesItemIdSessionsSessionIdRouteImport
      parentRoute: typeof AppCoursesCourseIdRoute
    }
  }
}

interface AppCoursesCourseIdRouteChildren {
  AppCoursesCourseIdLoadoutRoute: typeof AppCoursesCourseIdLoadoutRoute
  AppCoursesCourseIdShopRoute: typeof AppCoursesCourseIdShopRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdLessonsItemIdRoute: typeof AppCoursesCourseIdLessonsItemIdRoute
  AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute: typeof AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute
}

const AppCoursesCourseIdRouteChildren: AppCoursesCourseIdRouteChildren = {
  AppCoursesCourseIdLoadoutRoute: AppCoursesCourseIdLoadoutRoute,
  AppCoursesCourseIdShopRoute: AppCoursesCourseIdShopRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdLessonsItemIdRoute: AppCoursesCourseIdLessonsItemIdRoute,
  AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute:
    AppCoursesCourseIdPracticesItemIdSessionsSessionIdRoute,
}

const AppCoursesCourseIdRouteWithChildren =
  AppCoursesCourseIdRoute._addFileChildren(AppCoursesCourseIdRouteChildren)

interface AppRouteChildren {
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppMeRoute: typeof AppMeRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppPlayRoute: typeof AppPlayRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppShopRoute: typeof AppShopRoute
  AppWardrobeRoute: typeof AppWardrobeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppearanceRoute: AppAppearanceRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppMeRoute: AppMeRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppPlayRoute: AppPlayRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSearchRoute: AppSearchRoute,
  AppShopRoute: AppShopRoute,
  AppWardrobeRoute: AppWardrobeRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
